// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VietTuneArchive.Domain.Context;

#nullable disable

namespace VietTuneArchive.Domain.Context.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResearchCitation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TimestampEnd")
                        .HasColumnType("int");

                    b.Property<int?>("TimestampStart")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("RecordingId");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.AudioAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetectedInstrumentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectedKey")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DetectedTempo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpectralFeaturesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedEthnicGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SuggestedMetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.ToTable("AudioAnalysisResults");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Ceremony", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Ceremonies");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Commune", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Communes");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.EthnicGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LanguageFamily")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryRegion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EthnicGroups");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.EthnicGroupCeremony", b =>
                {
                    b.Property<Guid>("EthnicGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CeremonyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EthnicGroupId", "CeremonyId");

                    b.HasIndex("CeremonyId");

                    b.ToTable("EthnicGroupCeremonies");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConstructionMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OriginEthnicGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TuningSystem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OriginEthnicGroupId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.InstrumentEthnicGroup", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EthnicGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InstrumentId", "EthnicGroupId");

                    b.HasIndex("EthnicGroupId");

                    b.ToTable("InstrumentEthnicGroups");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.KBCitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Citation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("KBCitations");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.KBEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("KBEntries");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.KBRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.HasIndex("EntryId");

                    b.ToTable("KBRevisions");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.MusicalScale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NotePattern")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MusicalScales");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.QAConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QAConversations");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.QAMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrectedByExpertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpertCorrection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FlaggedByExpert")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SourceKBEntryIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceRecordingIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CorrectedByExpertId");

                    b.ToTable("QAMessages");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioFileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AudioFormat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("CeremonyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommuneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("EthnicGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("GpsLatitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GpsLongitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KeySignature")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LyricsOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyricsVietnamese")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MusicalScaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerformanceContext")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PerformerAge")
                        .HasColumnType("int");

                    b.Property<string>("PerformerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RecordingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tempo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoFileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("VocalStyleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("CommuneId");

                    b.HasIndex("EthnicGroupId");

                    b.HasIndex("MusicalScaleId");

                    b.HasIndex("UploadedById");

                    b.HasIndex("VocalStyleId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.RecordingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.ToTable("RecordingImages");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.RecordingInstrument", b =>
                {
                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlayingTechnique")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("RecordingId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("RecordingInstruments");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.RecordingTag", b =>
                {
                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecordingId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecordingTags");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContributorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContributorId");

                    b.HasIndex("RecordingId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.SubmissionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionVersions");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicCredentials")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ContributionScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.VectorEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.ToTable("VectorEmbeddings");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.VocalStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EthnicGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EthnicGroupId");

                    b.ToTable("VocalStyles");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Annotation", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.User", "Expert")
                        .WithMany("Annotations")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.Recording", "Recording")
                        .WithMany("Annotations")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.AudioAnalysisResult", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.Recording", "Recording")
                        .WithMany("AudioAnalysisResults")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Commune", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.District", "District")
                        .WithMany("Communes")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.District", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.EthnicGroupCeremony", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.Ceremony", "Ceremony")
                        .WithMany("EthnicGroupCeremonies")
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.EthnicGroup", "EthnicGroup")
                        .WithMany("EthnicGroupCeremonies")
                        .HasForeignKey("EthnicGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("EthnicGroup");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Instrument", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.EthnicGroup", "OriginEthnicGroup")
                        .WithMany("OriginInstruments")
                        .HasForeignKey("OriginEthnicGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OriginEthnicGroup");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.InstrumentEthnicGroup", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.EthnicGroup", "EthnicGroup")
                        .WithMany("InstrumentEthnicGroups")
                        .HasForeignKey("EthnicGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.Instrument", "Instrument")
                        .WithMany("InstrumentEthnicGroups")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EthnicGroup");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.KBCitation", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.KBEntry", "Entry")
                        .WithMany("KBCitations")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.KBEntry", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.User", "Author")
                        .WithMany("KBEntries")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.KBRevision", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.User", "Editor")
                        .WithMany("KBRevisions")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.KBEntry", "Entry")
                        .WithMany("KBRevisions")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editor");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.QAConversation", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.User", "User")
                        .WithMany("QAConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.QAMessage", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.QAConversation", "Conversation")
                        .WithMany("QAMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.User", "CorrectedByExpert")
                        .WithMany("CorrectedQAMessages")
                        .HasForeignKey("CorrectedByExpertId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Conversation");

                    b.Navigation("CorrectedByExpert");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Recording", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.Ceremony", "Ceremony")
                        .WithMany("Recordings")
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VietTuneArchive.Domain.Entities.Commune", "Commune")
                        .WithMany("Recordings")
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VietTuneArchive.Domain.Entities.EthnicGroup", "EthnicGroup")
                        .WithMany("Recordings")
                        .HasForeignKey("EthnicGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.MusicalScale", "MusicalScale")
                        .WithMany("Recordings")
                        .HasForeignKey("MusicalScaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VietTuneArchive.Domain.Entities.User", "UploadedBy")
                        .WithMany("Recordings")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.VocalStyle", "VocalStyle")
                        .WithMany("Recordings")
                        .HasForeignKey("VocalStyleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ceremony");

                    b.Navigation("Commune");

                    b.Navigation("EthnicGroup");

                    b.Navigation("MusicalScale");

                    b.Navigation("UploadedBy");

                    b.Navigation("VocalStyle");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.RecordingImage", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.Recording", "Recording")
                        .WithMany("RecordingImages")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.RecordingInstrument", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.Instrument", "Instrument")
                        .WithMany("RecordingInstruments")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.Recording", "Recording")
                        .WithMany("RecordingInstruments")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.RecordingTag", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.Recording", "Recording")
                        .WithMany("RecordingTags")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.Tag", "Tag")
                        .WithMany("RecordingTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Review", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.Submission", "Submission")
                        .WithMany("Reviews")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Submission", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.User", "Contributor")
                        .WithMany("Submissions")
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VietTuneArchive.Domain.Entities.Recording", "Recording")
                        .WithMany("Submissions")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.SubmissionVersion", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.Submission", "Submission")
                        .WithMany("SubmissionVersions")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.VectorEmbedding", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.Recording", "Recording")
                        .WithMany("VectorEmbeddings")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.VocalStyle", b =>
                {
                    b.HasOne("VietTuneArchive.Domain.Entities.EthnicGroup", "EthnicGroup")
                        .WithMany("VocalStyles")
                        .HasForeignKey("EthnicGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EthnicGroup");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Ceremony", b =>
                {
                    b.Navigation("EthnicGroupCeremonies");

                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Commune", b =>
                {
                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.District", b =>
                {
                    b.Navigation("Communes");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.EthnicGroup", b =>
                {
                    b.Navigation("EthnicGroupCeremonies");

                    b.Navigation("InstrumentEthnicGroups");

                    b.Navigation("OriginInstruments");

                    b.Navigation("Recordings");

                    b.Navigation("VocalStyles");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("InstrumentEthnicGroups");

                    b.Navigation("RecordingInstruments");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.KBEntry", b =>
                {
                    b.Navigation("KBCitations");

                    b.Navigation("KBRevisions");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.MusicalScale", b =>
                {
                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.QAConversation", b =>
                {
                    b.Navigation("QAMessages");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Recording", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("AudioAnalysisResults");

                    b.Navigation("RecordingImages");

                    b.Navigation("RecordingInstruments");

                    b.Navigation("RecordingTags");

                    b.Navigation("Submissions");

                    b.Navigation("VectorEmbeddings");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Submission", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("SubmissionVersions");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.Tag", b =>
                {
                    b.Navigation("RecordingTags");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.User", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("AuditLogs");

                    b.Navigation("CorrectedQAMessages");

                    b.Navigation("KBEntries");

                    b.Navigation("KBRevisions");

                    b.Navigation("QAConversations");

                    b.Navigation("Recordings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("VietTuneArchive.Domain.Entities.VocalStyle", b =>
                {
                    b.Navigation("Recordings");
                });
#pragma warning restore 612, 618
        }
    }
}
