FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# copy toàn bộ backend
COPY . .

# restore bằng solution (CÁCH AN TOÀN NHẤT)
RUN dotnet restore VietTuneArchive.sln

# publish đúng project API
RUN dotnet publish VietTuneArchive/VietTuneArchive.API.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "VietTuneArchive.API.dll"]
